import Head from "next/head";
import { useRouter } from "next/router";
import type { BreadcrumbItemType } from "../../../../components/common/Breadcrumb";
import { Breadcrumb } from "../../../../components/common/Breadcrumb";
import type { NextPageWithLayout } from "../../../../components/layout/NextPageWithLayout";
import PublicLayout from "../../../../components/layout/PublicLayout";
import OlympicMedalsEditForm from "../../../../components/modules/OlympicModules/edit/OlympicMedalsEditForm";

const OlympicMedalsEdit: NextPageWithLayout = () => {
  const router = useRouter();
  const { olympicMedalId } = router.query;

  const breadcrumbItems: BreadcrumbItemType[] = [
    {
      url: `/olympic-medals`,
    },
    {
      label: "Country",
      url: `/olympic-medals/${olympicMedalId as string}`,
    },
    {
      label: "Edit",
    },
  ];

  return (
    <>
      <Head>
        <title>Olympic Medals Add</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex h-full w-full  flex-col justify-start">
        <Breadcrumb items={breadcrumbItems} />
        <div className="px-auto mt-6 flex w-full flex-col rounded-lg ">
          <OlympicMedalsEditForm />
        </div>
      </main>
    </>
  );
};

export default OlympicMedalsEdit;

OlympicMedalsEdit.getLayout = (page) => <PublicLayout>{page}</PublicLayout>;
