import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";

import { MdModeEditOutline } from "react-icons/md";
import { BsTrashFill } from "react-icons/bs";

import { OlympicMedalDeleteModal } from "../../../components/modules/OlympicModules/single/OlympicMedalDeleteModal";
import type { BreadcrumbItemType } from "../../../components/common";
import { CustomIconButton, Breadcrumb } from "../../../components/common";
import type { NextPageWithLayout } from "../../../components/layout";
import { PublicLayout } from "../../../components/layout";
import { OlympicMedalDetails } from "../../../components/modules/OlympicModules/single";

const OlympicMedal: NextPageWithLayout = () => {
  const router = useRouter();
  const { olympicMedalId } = router.query;
  const [open, setOpen] = useState<boolean>(false);

  const breadcrumbItems: BreadcrumbItemType[] = [
    {
      url: `/olympic-medals`,
    },
    {
      label: `Country`,
    },
  ];

  return (
    <>
      <Head>
        <title>Olympic Medals</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex h-full w-full max-w-3xl flex-col justify-start">
        <div className="flex w-full justify-between">
          <Breadcrumb items={breadcrumbItems} />
          <div className="flex gap-x-2">
            <CustomIconButton
              icon={MdModeEditOutline}
              className="rounded-md p-0.5 text-2xl text-slate-600 transition  hover:text-slate-400"
              href={`/olympic-medals/${olympicMedalId as string}/edit`}
            />
            <CustomIconButton
              icon={BsTrashFill}
              className="cursor-pointer rounded-md p-0.5 text-2xl text-slate-600  transition hover:text-rose-500"
              onClick={() => setOpen(true)}
            />
          </div>
        </div>
        <div>
          <OlympicMedalDetails />
        </div>
        <OlympicMedalDeleteModal open={open} setOpen={setOpen} />
      </main>
    </>
  );
};

export default OlympicMedal;

OlympicMedal.getLayout = (page) => <PublicLayout>{page}</PublicLayout>;
