import Head from "next/head";
import type { BreadcrumbItemType } from "../../components/common/Breadcrumb";
import { Breadcrumb } from "../../components/common/Breadcrumb";
import { PlusButton } from "../../components/common/PlusButton";
import type { NextPageWithLayout } from "../../components/layout";
import { PublicLayout } from "../../components/layout";

import { OlympicMedalsDatatable } from "../../components/modules/OlympicModules/list/OlympicMedalsDatatable";

const OlympicMedals: NextPageWithLayout = () => {
  const breadcrumbItems: BreadcrumbItemType[] = [
    {
      url: `/olympic-medals`,
    },
    {
      label: "Olympic Medals",
    },
  ];

  return (
    <>
      <Head>
        <title>Olympic Medals</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full w-full flex-col justify-start">
        <div className="flex w-full justify-between">
          <Breadcrumb items={breadcrumbItems} />
          <PlusButton href={"/olympic-medals/add"} />
        </div>
        <div className="items-scenter flex w-full flex-col justify-center pt-8">
          <OlympicMedalsDatatable />
        </div>
      </main>
    </>
  );
};

export default OlympicMedals;

OlympicMedals.getLayout = (page) => <PublicLayout>{page}</PublicLayout>;
